cd\qsys_g\qfa_cl
copy qindex.dbf  c:\qsys_gins\Qfa_cl
copy qprogs.dbf  c:\qsys_gins\Qfa_cl
copy qstruct.dbf c:\qsys_gins\Qfa_cl
copy qbloc.glo   c:\qsys_gins\Qfa_cl
copy qcl_.exe    c:\qsys_gins\Qfa_cl
copy qconfig.dbf c:\qsys_gins\Qfa_cl

cd\qsys_g\qcp
copy qindex.dbf  c:\qsys_gins\Qcp
copy qprogs.dbf  c:\qsys_gins\Qcp
copy qstruct.dbf c:\qsys_gins\Qcp
copy qbloc.glo   c:\qsys_gins\Qcp
copy qcp_.exe    c:\qsys_gins\Qcp
copy qconfig.dbf c:\qsys_gins\Qcp


cd\qsys_g\qes
copy qindex.dbf  c:\qsys_gins\Qes
copy qprogs.dbf  c:\qsys_gins\Qes
copy qstruct.dbf c:\qsys_gins\Qes
copy qbloc.glo   c:\qsys_gins\Qes
copy qes_.exe    c:\qsys_gins\Qes
copy qconfig.dbf c:\qsys_gins\Qes


cd\qsys_g\qpg
copy qindex.dbf  c:\qsys_gins\Qpg
copy qprogs.dbf  c:\qsys_gins\Qpg
copy qstruct.dbf c:\qsys_gins\Qpg
copy qbloc.glo   c:\qsys_gins\Qpg
copy qpg_.exe    c:\qsys_gins\Qpg
copy qconfig.dbf c:\qsys_gins\Qpg



cd\qsys_g\qrb
copy qindex.dbf  c:\qsys_gins\Qrb
copy qprogs.dbf  c:\qsys_gins\Qrb
copy qstruct.dbf c:\qsys_gins\Qrb
copy qbloc.glo   c:\qsys_gins\Qrb
copy qrb_.exe    c:\qsys_gins\Qpg
copy qconfig.dbf c:\qsys_gins\Qpg


cd\qsys_g\qts
copy qindex.dbf  c:\qsys_gins\Qts
copy qprogs.dbf  c:\qsys_gins\Qts
copy qstruct.dbf c:\qsys_gins\Qts
copy qbloc.glo   c:\qsys_gins\Qts
copy qts_.exe    c:\qsys_gins\Qts
copy qconfig.dbf c:\qsys_gins\Qts


cd\qsys_g\qef
copy qindex.dbf  c:\qsys_gins\Qef
copy qprogs.dbf  c:\qsys_gins\Qef
copy qstruct.dbf c:\qsys_gins\Qef
copy qbloc.glo   c:\qsys_gins\Qef
copy qef_.exe    c:\qsys_gins\Qef
copy qconfig.dbf c:\qsys_gins\Qef


cd\qsys_g\qct
copy qindex.dbf  c:\qsys_gins\Qct
copy qprogs.dbf  c:\qsys_gins\Qct
copy qstruct.dbf c:\qsys_gins\Qct
copy qbloc.glo   c:\qsys_gins\Qct
copy qct_.exe    c:\qsys_gins\Qct
copy qconfig.dbf c:\qsys_gins\Qct



