echo SET PLL=\QSYS_G\QSHARE >> AUTOEXEC.BAT
echo SET CLIPPER= //F140 //DYNF:8 //SWAPK:65535 //SWAPPATH:"\QSYS_G" //TEMPPATH:"\QSYS_G" >> AUTOEXEC.BAT
echo SET PATH=C:\WINDOWS;C:\WINDOWS\COMMAND;C:\QSYS_G\QUTIL >> AUTOEXEC.BAT
ECHO FILES=200 >> CONFIG.SYS
ECHO BUFFERS=30,0 >> CONFIG.SYS
