CD\QSYS_G\QCT\E901
PKZIP c:\docume~1\alluse~1\desktop\E901 *.DBF -EX
CD\QSYS_G\QCT\E902
PKZIP c:\docume~1\alluse~1\desktop\E902 *.DBF -EX
CD\QSYS_G\QCT\E903
PKZIP c:\docume~1\alluse~1\desktop\E903 *.DBF -EX
CD\QSYS_G\QCT\E904
PKZIP c:\docume~1\alluse~1\desktop\E904 *.DBF -EX
CD\QSYS_G\QCT\E905
PKZIP c:\docume~1\alluse~1\desktop\E905 *.DBF -EX
CD\QSYS_G\QCT\E906
PKZIP c:\docume~1\alluse~1\desktop\E906 *.DBF -EX

